export const BASE_PATH = 'http://192.237.214.190';
export const LOGIN = '/api/v1/login/';
export const LOGOUT = '/api/v1/logout/';
export const FORGOT_PASSWORD = '/api/v1/password-reset/';
export const FACEBOOK_LOGIN = '/api/v1/fb-login/';
export const GOOGLE_LOGIN = '/api/v1/google-login/';
export const SIGN_UP = '/api/v1/registration/';
export const LIST_POI = '/api/v1/get-poi/';
export const MAP_API_KEY = 'AIzaSyC_AuBLEOSNKzsDpQ2Psu3MrNId9FygmRM';
export const TERMS_AND_CONDITIONS = '/api/v1/terms-and-conditions/';

export const ABOUT_US = '/api/v1/about-us/';
export const HELP = '/api/v1/help/';
export const FAQ = '/api/v1/faq/';
export const LIST_LOCATION = '/api/v1/locations/';
export const USER_PROFILE = '/api/v1/user/detail/';
export const LIST_POI_CATEGORIES = '/api/v1/get-poi-categories/';
export const HUNT_DETAILS = '/api/v1/scavenger/hunts/detail/';
export const ACTIVE_HUNTS = '/api/v1/scavenger/hunts/get-hunts';
export const GET_IMAGES = '/api/v1/get-images/';
export const USER_CHECKINS = '/api/v1/user-checkins/';
export const USER_PROFILE_UPDATE = '/api/v1/user-checkins/';
export const GET_POI_CATEGORIES = '/api/v1/get-poi-categories/';
export const FILTER = '/api/v1/get-all-winery/';
export const SEARCH = '/api/v1/search-poi/';
export const GET_DISTANCE = 'https://maps.googleapis.com/maps/api/distancematrix/json';
export const GET_HUNTS = '/api/v1/scavenger/hunts/get-hunts/';
export const GET_HUNT_DETAILS = '/api/v1/scavenger/hunts/detail/';
export const START_TASK = '/api/v1/start-task/';
export const COMPLETE_TASK = '/api/v1/complete-task/';
export const GET_SOCIAL_IMAGES = '/api/v1/get-images/';
export const GET_HUNT_IMAGES = '/api/v1/task-photo-stream/';
export const GET_COORDINATES = '/api/v1/get-kml/';
export const GET_NEARBY_RESTAURANTS = '/api/v1/get-all-winery/?category_id=17';
export const GET_NEARBY_LODGES = '/api/v1/get-all-winery/?category_id=18';
export const GET_NEARBY_WINERIES = '/api/v1/get-all-winery/?category_id=19';
export const REPORT_ISSUE = '/api/v1/create-contact/';
export const GET_SVG = '/api/v1/svgs/';
export const GET_ISSUE_CATEGORIES = '/api/v1/issue-categories/';
export const CATEGORY_SEARCH = '/api/v1/winery-search/';
export const TRAIL_TOUR_SWITCH='/api/v1/save-state/';
export const TRAIL_TOUR_LIST='/api/v1/get-clusters/';
export const VIDEOS='/api/v1/vimeo-list/';
export const POST_LOCATION='/api/v1/get-point-of-interest/';
export const POST_DEVICE_TOKEN='https://mobile.vinetrail.org/api/v1/register-device/';
export const REGISTER_DEVICE_ANDROID='/api/v1/register-gcm-device/';
export const REGISTER_DEVICE_IOS='/api/v1/register-device/';
export const GET_NOTIFICATION_LIST='/api/v1/user-notifications/';
export const GET_REPORT_ABUSE_CATEGORY='/api/v1/list-social-complaints/';
export const REPORT_ABUSE='/api/v1/report-post/';

