//Explore
export const SET_POIS = 'SET_POIS';
export const CLEAR_POIS = 'CLEAR_POIS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const FILTERED_POI = 'FILTERED_POI';
export const SET_DISTANCE = 'SET_DISTANCE';
export const SET_LODGES_DISTANCE = 'SET_LODGES_DISTANCE';
export const SET_WINERIES_DISTANCE = 'SET_WINERIES_DISTANCE';
export const SET_COORDINATES = 'SET_COORDINATES';
export const SET_MARKER_DISTANCE = 'SET_MARKER_DISTANCE';
export const SET_POI = 'SET_POI';
//Navigation
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const SIGNUP_SCREEN = 'SIGNUP_SCREEN';
export const PASSWORD_RESET_SCREEN = 'PASSWORD_RESET_SCREEN';
export const JOIN_US_SCREEN = 'JOIN_US_SCREEN';
export const BOTTOM_NAVIGATOR = 'BOTTOM_NAVIGATOR';
export const MAP_DETAIL_SCREEN = 'MAP_DETAIL_SCREEN';
export const MAP_POINTER_DETAIL_SCREEN = 'MAP_POINTER_DETAIL_SCREEN';
export const MAP_DIRECTION_SCREEN = 'MAP_DIRECTION_SCREEN';
export const EXPLORE_SCREEN = 'EXPLORE_SCREEN';
export const TUTORIAL_SCREEN = 'TUTORIAL_SCREEN';

//Scavenger Navigator
export const SCAVENGER_HUNT = 'SCAVENGER_HUNT';
export const SCAVENGER_HUNT_INSTRUCTION_SCREEN = 'SCAVENGER_HUNT_INSTRUCTION_SCREEN'
export const SCAVENGER_HUNT_DETAILS_SCREEN = 'SCAVENGER_HUNT_DETAILS_SCREEN';
export const SCAVENGER_HUNT_CLUE_SCREEN = 'SCAVENGER_HUNT_CLUE_SCREEN';
export const SCAVENGER_HUNT_CONGRATULATION_SCREEN = 'SCAVENGER_HUNT_CONGRATULATION_SCREEN';
export const SCAVENGER_HUNT_TRY_AGAIN_SCREEN = 'SCAVENGER_HUNT_TRY_AGAIN_SCREEN';
export const SCAVENGER_HUNT_VERIFICATION_SCREEN = 'SCAVENGER_HUNT_VERIFICATION_SCREEN';
export const HUNT_IMAGES_SCREEN = 'HUNT_IMAGES_SCREEN';

// Bottom Navigation
export const DASHBOARD = 'DASHBOARD';
export const MAP = 'MAP';
export const NEARBY = 'NEARBY';
export const REPORT = 'REPORT';
export const TRIAL_TOUR = 'TRIAL_TOUR';

//Session
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';
export const SET_LOGOUT_ERROR = 'SET_LOGOUT_ERROR';
export const CLEAR_LOGOUT_ERROR = 'CLEAR_LOGOUT_ERROR';
export const SET_SUCCESS_STATUS = 'SET_SUCCESS_STATUS';

//User
export const SET_SIGNUP_RESULT = 'SET_SIGNUP_RESULT';
export const CLEAR_SIGNUP_RESULT = 'CLEAR_SIGNUP_RESULT';
export const SET_SIGNUP_ERROR = 'SET_SIGNUP_ERROR';
export const CLEAR_SIGNUP_ERROR = 'CLEAR_SIGNUP_ERROR';

//hunts
export const SET_HUNTS = 'SET_HUNTS';
export const SET_HUNT_DETAILS = 'SET_HUNT_DETAILS';
export const START_TASK = 'START_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';

//social
export const SOCIAL = 'SOCIAL';
export const SET_HUNT_IMAGES = 'SET_HUNT_IMAGES';
export const SET_SOCIAL_IMAGES = 'SET_SOCIAL_IMAGES';
export const SET_REPORT_ABUSE_CATEGORY = 'SET_REPORT_ABUSE_CATEGORY';
export const REPORT_ABUSE_STATUS = 'REPORT_ABUSE_STATUS';
export const REPORT_ABUSE = 'REPORT_ABUSE';

//Restaurants
export const RESTAURANTS = 'RESTAURANTS';
export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const RESTAURANTS_DETAIL = 'RESTAURANTS_DETAIL';
export const LODGE_SCREEN = 'LODGE_SCREEN';
export const WINERIES_SCREEN = 'WINERIES_SCREEN';
export const POI_MAP_DIRECTION_SCREEN = 'POI_MAP_DIRECTION_SCREEN';
export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS';

//settings
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
export const ABOUT_US_SCREEN = 'ABOUT_US_SCREEN';
export const HELP_SCREEN = 'HELP_SCREEN';
export const TERMS_AND_CONDITION_SCREEN = 'TERMS_AND_CONDITION_SCREEN';
export const FAQ_SCREEN = 'FAQ_SCREEN';
//nearBy
export const SET_NEARBY_RESTAURANTS = 'SET_NEARBY_RESTAURANTS';
export const SET_NEARBY_LODGES = 'SET_NEARBY_LODGES';
export const SET_NEARBY_WINERIES = 'SET_NEARBY_WINERIES';
export const NEARBY_DETAIL_SCREEN = 'NEARBY_DETAIL_SCREEN';
export const NEARBY_DIRECTION_SCREEN = 'NEARBY_DIRECTION_SCREEN';
export const NEARBY_RESTAURANTS = 'NEARBY_RESTAURANTS';
export const NEARBY_WINERIES = 'NEARBY_WINERIES';
export const NEARBY_LODGES = 'NEARBY_LODGES';
//misc
export const SET_ABOUT_US = 'SET_ABOUT_US';
export const SET_HELP = 'SET_HELP';
export const SET_TERMS_AND_CONDITIONS = 'SET_TERMS_AND_CONDITIONS';
export const SET_FAQ = 'SET_FAQ';
export const REPORT_ISSUE = 'REPORT_ISSUE';
export const SET_SVG = 'SET_SVG';
export const REPORT_STATUS = 'REPORT_STATUS';
//section map
export const SECTION_MAP = 'SECTION_MAP';
export const SVG_IMAGE_SCREEN = 'SVG_IMAGE_SCREEN';
export const SET_ISSUE_CATEGORY = 'SET_ISSUE_CATEGORY';
export const SET_CATEGORY_SEARCH_RESULT = 'SET_CATEGORY_SEARCH_RESULT';

//trailTour

export const TRAIL_SWITCH_LIST = 'TRAIL_SWITCH_LIST';
export const TRAIL_SWITCH = 'TRAIL_SWITCH';

//Notofication

export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';

export const VIDEO_SCREEN = 'VIDEO_SCREEN';
export const SET_VIDEOS = 'SET_VIDEOS';
export const PLAY_VIDEO_SCREEN = 'PLAY_VIDEO_SCREEN';
export const POST_LOCATION_RESULT = 'POST_LOCATION_RESULT';
export const POST_DEVICE_TOKEN = 'POST_DEVICE_TOKEN';
export const SET_NOTIFICATION_LIST = 'SET_NOTIFICATION_LIST';