# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vinetrail' do
    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'
    
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
    ]
    
    pod 'react-native-maps', path: rn_maps_path
    
    pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
    
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vinetrail

    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
#    pod 'GoogleSignIn'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'


  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'vinetrailTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'vinetrail-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vinetrail-tvOS

  target 'vinetrail-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
